/*
 * fsm_template_token.h
 *
 *  Created on: 2016年6月26日
 *      Author: light
 */

#ifndef SRC_CTEMPLATE_FSM_TEMPLATE_TOKEN_H_
#define SRC_CTEMPLATE_FSM_TEMPLATE_TOKEN_H_

enum FSM_TEMPLATE_H_TOKER{
	EFTT_FSM_H_FSMNAME = 0,
	EFTT_FSM_H_FSMUPNAME,
	EFTT_FSM_H_STATE_LIST,
	EFTT_FSM_H_EVENT_LIST,
	EFTT_FSM_C_INCLUDE_STATE_HEADER_LIST,
	EFTT_FSM_C_FSMNAME_STATE,
	EFTT_FSM_C_STATE_INIT_FUNC_LIST,
	EFTT_STATE_FSMNAME_INIT_STATE_FUNC,
	EFTT_FSM_MAX
};

extern const char* fsm_template_token[EFTT_FSM_MAX];

#endif /* SRC_CTEMPLATE_FSM_TEMPLATE_TOKEN_H_ */
